version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: ai_service_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_service_network

  redis:
    image: redis:latest
    container_name: ai_service_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_service_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ai_service_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ai_service_network

networks:
  ai_service_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: